### ISSUE TITLE
New Game Request!

### ISSUE THREAD

**Issue by TrickJoker312** [OddPvP/unblockedgames#11]
Hey! I wanted to know if you could add the Lofi funkin from the Friday Night Funkin game?
I would greatly appreciate it!

**Comment by sourcevalue** [comment]
Hello! Odd the main project manager added the regular friday night funkin to the site. Sadly he could not add the "Lofi funkin" mod to the game. 

Sorry for the inconvience.

**Comment by sourcevalue** [comment]
Hello! Odd the main project manager added the regular friday night funkin to the site. Sadly he could not add the "Lofi funkin" mod to the game. 

Sorry for the inconvience.
