### ISSUE TITLE
[OTHER] what is floyd

### ISSUE THREAD

**Issue by coolestniceguy21** [OddPvP/unblockedgames#12]
when i click on the file all it shows is an index. what game is it? just in case theres an ip logger or osmetihng

**Comment by OddPvP** [comment]
A hidden game that I added for one of my friends. It doesn't show on the public game list so its nothing to worry about.

**Comment by coolestniceguy21** [comment]
whats it about though? just if i want to add it

**Comment by OddPvP** [comment]
It's about police brutality.

**Comment by coolestniceguy21** [comment]
elaborate
