### ISSUE TITLE
some of the games just do NOT work

### ISSUE THREAD

**Issue by truesupersaiyan** [OddPvP/unblockedgames#16]
**Describe the bug**
Games won't load
**To Reproduce**
1.????
2.like male on female reproductionw hat
3.

**Additional context**
games affected (that i know) -
[
Dune
ducklife 2
ducklife 1
]
do you have a playtester to check if the games work or

**Comment by truesupersaiyan** [comment]
NOT kitchen gun game (it just takes a bit to load)

**Comment by OddPvP** [comment]
Interactive buddy also works just takes time to load but yes I see Dune, ducklife 2 and ducklife 1 don't work, I will look into this soon.
