### ISSUE TITLE
[QUESTION] How do we add our own games to the site?

### ISSUE THREAD

**Issue by KeiranGamingTV** [OddPvP/unblockedgames#24]

**Comment by IcyonGit** [comment]
in the index.html file add this line of code and change the necessary placeholders
`<a id="1 (2048 game)" class="link" href="./play/urgame/" target="_blank"><span class="bar"></span><img src="./icons/placeholder.webp" alt="your game here"><b>placeholder</b></a>

**Comment by Vxmphtd** [comment]
How do I add it to my thing Im on school chromebook

**Comment by sourcevalue** [comment]
You can get an extension called Caret. Its not the best but works great on school chromebooks, if its a github site you can just edit it on github.
