### ISSUE TITLE
[BUG] Fruit Ninja and Escaping the prison

### ISSUE THREAD

**Issue by MahirMahdi** [OddPvP/unblockedgames#25]
Fruit Ninja keeps loading and after some time the page breaks down

Escaping the prison shows an error 404

If I find more I'll let you know.😀

![Screenshot 2023-02-05 142316](https://user-images.githubusercontent.com/66949598/216808914-fc990c22-56bc-463c-98d3-57f1096cc8cc.png)
Fruit Ninja

![Screenshot 2023-02-05 142343](https://user-images.githubusercontent.com/66949598/216808922-9f17a5ab-956f-496a-b84e-1381e322f565.png)
Escaping the prison

**Comment by sourcevalue** [comment]
Thanks for telling us! Ill look into it shortly. Quick question what are site are you using?

**Comment by sourcevalue** [comment]
Okay that was fast. I published a small push. It isnt in the release. It will be in the next one.
For now just download it as a zip.

Or alternatively you could go ahead and change the id and the text to "escapingtheprison."

Although, this doesnt entirely fix it as the netlify on the main games.odd.gay site is down for some reason.
We will be fixing that soon.
