### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by XxRobloxSkullxX** [OddPvP/unblockedgames#29]
**Describe the bug**
The website odd.games.gay got blocked at my school and i need a new web address for the odd games I'm trying to make and i cant use your other 3 because they are blocked to so i kind of need another odd games web address so could make another odd games or give me a different odd games website address send to email owenc4444@gmail.com (i check my emails every day)
**To Reproduce**
1.
2.
3.

**Additional context**

**Comment by OddPvP** [comment]
Not a bug, Use one of the deployment methods from https://github.com/OddPvP/unblockedgames/blob/main/README.md to make your own so it won't get blocked.
