### ISSUE TITLE
[OTHER] DMCA

### ISSUE THREAD

**Issue by Asleep123** [OddPvP/unblockedgames#30]
Hi, this is a DMCA notice from https://3kh0.github.io/ .

I work on the "legal" team (unofficial) for this website. I hereby request takedown of your game "PaperIO 2" as this infringes on our license.

If you refuse to take down this part within 48 hours, we will file DMCA.

- Asleep, 3kh0 Legal Team

**Comment by Asleep123** [comment]
You do not have to take down your website, just this part.

**Comment by IcyonGit** [comment]
> Hi, this is a DMCA notice from https://3kh0.github.io/ .
> 
> I work on the "legal" team (unofficial) for this website. I hereby request takedown of your game "PaperIO 2" as this infringes on our license.
> 
> If you refuse to take down this part within 48 hours, we will file DMCA.
> 
> * Asleep, 3kh0 Legal Team

Please explain how a game that 3kh0 doesn't own can be DMCA-claimed. it doesn't work like that. just because a game is on your site doesn't mean you own it. paper.io is the intellectual property of Voodoo, not 3kh0. if you're going to have a legal team maybe don't hire idiots and instead people who actually have degrees.

**Comment by IcyonGit** [comment]
> Man. It might not be against the law, but it's really not cool to copy others things that they spent time on. We can still report it and get it taken down. And we aren't gonna hire professional lawyers, we ain't that serious.

3kh0 copied the game first. it's a publicly available game free to download and play. all 3kh0 did was rip the website files and rehost them, and if you're going to go as far as to have a legal team then hire people who at least know what they are talking about or don't have a legal team at all.

**Comment by IcyonGit** [comment]
> Man. It might not be against the law, but
IF. IT'S. NOT. AGAINST. THE. LAW. THEN. YOU. HAVE. NO. RIGHT. TO. TAKE. IT. DOWN.

**Comment by Drag0nA13x** [comment]
No fucking way this guy said he thought DMCAing you was a good idea

**Comment by Drag0nA13x** [comment]
And considering he didn’t file it, he’s bluffing to make you follow his orders

**Comment by OddPvP** [comment]
> No fucking way this guy said he thought DMCAing you was a good idea

I know hes bluffing 3kh0 himself tried to get all of our games taken down even other open source ones like 2048 cupcake.

**Comment by sourcevalue** [comment]
You can not DMCA stolen content 😄 

> Hi, this is a DMCA notice from https://3kh0.github.io/ .
> 
> I work on the "legal" team (unofficial) for this website. I hereby request takedown of your game "PaperIO 2" as this infringes on our license.
> 
> If you refuse to take down this part within 48 hours, we will file DMCA.
> 
> * Asleep, 3kh0 Legal Team
