### ISSUE TITLE
What happened to the minecraft (precision client)?

### ISSUE THREAD

**Issue by P1X3LMANTYL3R** [OddPvP/unblockedgames#34]
I used to use this all the time and i wonder why LITERALLY YESTERDAY you took it down. (i am big sad 😞)

--- PixelmanTyler
![bitmoji](https://sdk.bitmoji.com/render/panel/0c62d877-a0fb-4266-89d5-4d80ec96324f-025fb99e-6777-4a96-a6bc-771e461237e5-v1.png?transparent=1&palette=1&width=140)

**Comment by liam3242** [comment]
Yeah I am with you where did Minecraft go that was like the only game I played on their.

**Comment by OddPvP** [comment]
Mojang sent us a DMCA so we legally had to take it down, Sorry but there is nothing I can do.
