### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by TrickJoker312** [OddPvP/unblockedgames#9]
How do i create a repository, while trying to put this site on my site, without it redirecting?

**Comment by OddPvP** [comment]
You where probably forking out old repository try using this one https://github.com/OddPvP/unblockedgames/fork

**Comment by TrickJoker312** [comment]
Ok, thank you! I'll try.

**Comment by OddPvP** [comment]
Well I see on your profile you deployed it to github pages so I am guessing it worked! If you dont need anything else please close the issue!

**Comment by OddPvP** [comment]
Seems to be resolved
